name: Déploiement en Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest


    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Déploiement sur le Serveur de Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Commandes pour déployer votre application sur le serveur
            # Exemple : cd /chemin/vers/votre/application && git pull && docker-compose up -d
